name: Zendu Forms Deploy

on:
  push:
    branches:
      - "main"
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.0]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./
        run: npm install && npm run build:prod && cp dist/zenduit-ng-assignment/browser/index.html dist/zenduit-ng-assignment/browser/404.html
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: zenduit-pages # The branch the action should deploy to.
          folder: dist/zenduit-ng-assignment # The folder the action should deploy.        
