name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.0]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./zenduit-ng-assignment
        run: npm install && npm run build:prod && cp docs/browser/index.html
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: angular-crash-2021/dist/angular-crash # The folder the action should deploy.        
